apiVersion: v1
kind: Service
metadata:
  name: website-demo
  labels:
    app: website-demo
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: website-demo
    tier: website-demo
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-demo
  labels:
    app: website-demo
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: website-demo
  template:
    metadata:
      labels:
        app: website-demo
        tier: website-demo
    spec:
      containers:
      - image: 10.9.3.96:5000/website-demo:xxx
        name: website-demo
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "128Mi"
        ports:
        - containerPort: 80
          name: website-demo


